### ISSUE TITLE
Stopping help-view and greetservice-impl breaks the application

### ISSUE THREAD

**Issue by edler-san** [vaadin/base-starter-flow-karaf#37] opened 2021-04-13 10:46 UTC
After going through the steps from https://github.com/vaadin/base-starter-flow-karaf#build-and-run-a-vaadin-web-application-osgi-bundle I stopped both help-view and greetservice-impl. When refreshing the application in the browser (at localhost:8181) I get a blank page and the loading indicator never gets past the last few percent. No exceptions are found in karaf.log.

**Comment by denis-anisimov** [comment] 2021-04-13 11:58
Wrong repo and this is a duplicate of
https://github.com/vaadin/osgi/issues/58

**Closed by denis-anisimov** 2021-04-13 11:58 UTC
